OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"

